# Assignment 2

## Question 1 :-Write a python program to take a 3X3 matrix as a user input. Convert the matrix into numpy array. Print the matrix, rank, shape of the matrix. ?

In [65]:
import numpy as np
raw = int(input("Enter the no of Raws : \n"))
column = int(input("Enter the no of Column : \n"))
mat=[]
for i in range(raw*column):
    a=int(input())
    mat.append(a)
mat=np.array(mat).reshape(raw,column)
print(mat)
print(np.ndim(mat))
print(np.shape(mat))

Enter the no of Raws : 
3
Enter the no of Column : 
3
1
2
3
4
5
6
7
8
9
[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)


## Question 2 :- Write a function that generates 10 integers and use it to build an array 

In [51]:
import numpy as np
array=np.random.randint(np.random.randint(1000), size=10)
print(array,"\n",array.shape)

[37 29 18 52 13  2 41 21 32 47] 
 (10,)


## Question 3 :- Create a random vector (1D array) of size 10 and sort it 

In [64]:
import numpy as np
array=np.random.randint(np.random.randint(1000), size=10)
print(sorted(array))
#print(array,"\n",array.shape)

[9, 30, 128, 151, 208, 219, 223, 257, 280, 314]


## Question 4 :- Write a Python program to generate five random numbers from the normal distribution.
#### [Hint: use np.random.normal] 

In [63]:
import numpy as np

randInt=np.random.normal(0,0.1,(5))
print(randInt)

[-0.05240866  0.0112935  -0.00222529  0.0961996   0.00301755]


## Question 5 :-
### Write a numpy program program to add and subtract two random matrices. The size of the matrix will a user input. All the matrix element should be a positive integer value. Suppose 'A' and 'B' are two matrix. All the value of 'A' matrix cannot be greater than 10 and values of 'B' matrix cannot be greater than 20. 

In [79]:
Ar=int(input("Enter the no of raws in matrix : \n"))
Ac=int(input("Enter the no of Column's  in matrix : \n"))


A=np.random.randint(0,10,(Ar*Ac)).reshape(Ar,Ac)

B=np.random.randint(0,20,(Ar*Ac)).reshape(Ar,Ac)

Sum=A+B
Diff=A-B
print(A)
print(B,"\n \n",Sum,"\n \n",Diff)

Enter the no of raws in matrix : 
3
Enter the no of Column's  in matrix : 
3
[[8 1 5]
 [1 4 2]
 [2 2 8]]
[[13  4  3]
 [ 6 10 13]
 [14 19  2]] 
 
 [[21  5  8]
 [ 7 14 15]
 [16 21 10]] 
 
 [[ -5  -3   2]
 [ -5  -6 -11]
 [-12 -17   6]]


## Question 6 :-
### Write a numpy program program to multiply two random matrices. The size of the matrices will a user input. All the matrix element should be a positive integer value. Suppose 'A' and 'B' are two matrix. All the value of 'A', 'B' matrices cannot be greater than 10.  

In [7]:
import numpy as np  #Numpy is imported as np

Ar,Ac,Br,Bc=map(int,input("Enter the no of Sizes of matrces (Seperated by a space)x : \n").split())

#Ar,Ac are the raw and column of matrix A simillarly Br and Bc are raw and column of matrix B 

A=np.random.randint(0,10,(Ar*Ac)).reshape(Ar,Ac) #Creating the matrix of given size with the random elements ie below 10
B=np.random.randint(0,10,(Br*Bc)).reshape(Br,Bc)  #Creating the matrix of given size with the random elements ie below 10

mulAb= np.matmul(A,B)            #matrix multiplication in numpy

print("A \n",A,"\n\n","B \n",B,"\n\n",mulAb) #printing the result in the prescrirbed format

Enter the no of Sizes of matrces (Seperated by a space)x : 
1 2 2 3
A 
 [[1 7]] 

 B 
 [[7 1 9]
 [5 6 4]] 

 [[42 43 37]]


# Question 7 :-
### Write a python program 4.py to take nXm matrix as a user input. 'n' and 'm' are command line argument which are separated by a space.
### Where n >= 3 and 0>=m<=7. If this condition is false, ask the user to enter the 'n' and 'm' again. Create a zero matrix with same dimension and convert all columns in the matrix into a fibonacci series.
### For ith column, the first element should be the sum of i+(i-1) value. Print this matrix on the terminal. ?

In [18]:
import numpy as np

def fibo(n): 
    a=0
    b=1
    fib=np.array([a,b])
    if(n<0): 
        print("Incorrect input") 
    elif (n==0): 
        return a 
    elif (n==1): 
        return b 
    else: 
        for i in range(2,n): 
            c=a+b
            #print(c)
            a=b 
            b=c 
            fib=np.append(fib,c)
        return fib 

while True:
    n,m=map(int,input("Enter the N and M of the NxM matrix : \n").split())
    if (not(n>=3 and (0<m<=7))):
        continue
    else:
        matA=np.zeros((n,m))
        
        for i in range(m):
            i+=1
            matA[0,i-1:i]=i+(i-1)
        for i in range(1,n):
            matA[i:,:]=fibo(m)
        print(matA)
        break

Enter the N and M of the NxM matrix : 
5 6
[[ 1.  3.  5.  7.  9. 11.]
 [ 0.  1.  1.  2.  3.  5.]
 [ 0.  1.  1.  2.  3.  5.]
 [ 0.  1.  1.  2.  3.  5.]
 [ 0.  1.  1.  2.  3.  5.]]
