#  Numpy Assignment 3

## Exercise 1: How to replace items that satisfy a condition with another value in numpy array?

### Replace all odd numbers in arr with -1

In [2]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr)
arr[((arr >0) & (arr%2!=0))]=-1

print(arr)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Exercise 2: How to reshape an array? (2 Points)
### Convert a ID array to a 2D array with 2 rows 

In [6]:
arr = np.arange(10)
arr=arr.reshape(2,5)
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


## Exercise 3: How to generate custom sequences in numpy without hardcoding?

### Create the following pattern without hardcoding. Use only numpy functions and the below input array 

In [13]:
arr =np.array([1,2,3])
np.r_[np.repeat(arr[0], 2),np.repeat(arr[1:], 3), np.tile(arr, 3)]

array([1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

## Exercise 4: How to get the common items between two python numpy arrays?
### Get the common items between a and b


In [14]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)

array([2, 4])

## Exercise 5: How to get the positions where elements of two arrays match?
### Get the positions where elements of a and b match

In [21]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

pos=np.where(a==b)
print(pos)

(array([1, 3, 5, 7], dtype=int64),)


## Exercise 6: How to create a 2D array containing random floats between 5 and 10?

### Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

In [24]:
np.random.randint(5,10,(5*3)).reshape(5,3)

array([[9, 9, 7],
       [8, 8, 7],
       [9, 8, 6],
       [9, 5, 8],
       [7, 7, 7]])

## Exercise 7: How to limit the number of items printed in output of numpy array to 6?
### Limit the number of items printed in python numpy array a to a maximum of 6 elements.

In [27]:
np.set_printoptions(threshold=6)

arr = np.arange(15)
print(arr)

[ 0  1  2 ... 12 13 14]


## Exercise 8: How to pretty print a numpy array by suppressing the scientific notation (like 1el0)?
### Limit the number of items printed in python numpy array a to a maximum of 6 elements.

In [30]:
np.set_printoptions(suppress='false',threshold=6)

np.random.seed(100)
rand_arr=np.random.random([3,3])/1e3

print(rand_arr)

[[0.0005434  0.00027837 0.00042452]
 [0.00084478 0.00000472 0.00012157]
 [0.00067075 0.00082585 0.00013671]]


## Exercise 9: How to swap two columns in a 2d numpy array?
### Swap columns 1 and 2 in the array arr.

In [36]:
arr = np.arange(9).reshape(3,3)

print(arr)
arr[:,[1,2]]=arr[:,[2,1]]

print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 2 1]
 [3 5 4]
 [6 8 7]]


## Exercise 1 0: How to swap two rows in a 2d numpy array?
### Swap rows 1 and 2 in the array arr:

In [38]:
arr = np.arange(9).reshape(3,3)

print(arr)

arr[[1,2],:]=arr[[2,1],:]

print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [6 7 8]
 [3 4 5]]
