# Assignment no :01

### Question No: 01 Multiply 2 matrices

In [1]:
import numpy as np #importing numpy

X = np.array([[1, 4, 3],[3, 5, 6],[6, 7, 9]]) #initializing X and Y
Y = np.array([[1, 2, 5, 12],[6, 7, 3, 0],[4, 7, 9, 11]])

#printing X and Y and their shape

print(X,"\n shape of X : ", X.shape,"\n")
print(Y,"\n shape of Y : ",Y.shape)

Z=np.dot(X,Y) #Matrix Multiplication 
print(Z,"\n shape of Z : ",Z.shape)


[[1 4 3]
 [3 5 6]
 [6 7 9]] 
 shape of X :  (3, 3) 

[[ 1  2  5 12]
 [ 6  7  3  0]
 [ 4  7  9 11]] 
 shape of Y :  (3, 4)
[[ 37  51  44  45]
 [ 57  83  84 102]
 [ 84 124 132 171]] 
 shape of Z :  (3, 4)


### Question No: 02 -  Extract all numbers divisible by 3 from the array

In [2]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9,10,11,12]) #input array
#print(arr) #printing array
arr[(arr >0) & (arr%3==0)] #Selecting the array elements which satisfies the two conditions 
#print(arr[(arr >0) & (arr%3==0)]) 

array([ 3,  6,  9, 12])

### Question No: 03 -  Get the unique common items between a and b

In [3]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8]) #initialize the two arrays

np.intersect1d(a,b) #finding the unique values of a and b

array([2, 4])

### Question No: 04 -How to remove from one array those items that exist in another?

From array a remove all items present in array b

In [131]:
a = np.array([1,2,3,4,5,11,22,33,44,55])
b = np.array([5,6,7,8,9,10,11])
#print(a,b)

np.setdiff1d(a,b) 

#setdiff1d - Find the set difference of two arrays. 
#Return the sorted, unique values in ar1 that are not in ar2.

array([ 1,  2,  3,  4, 22, 33, 44, 55])

### Question No: 05. How to get the positions where elements of two arrays match?

Get the positions where elements of a and b match

In [133]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

print(a,b)

np.where(a == b)

[1 2 3 2 3 4 3 4 5 6] [ 7  2 10  2  7  4  9  4  9  8]


(array([1, 3, 5, 7], dtype=int64),)

### Question No: 06. How to create a 2D array containing random floats between 10 and 25?

Create a 2D array of shape 5x3 to contain random decimal numbers between 10 and 25.

In [40]:
#a=np.random.ranf((10,25))
a=np.zeros(3*5) # creating a 1D array of 3*5 elemets 0

for i in range(15):                  #Begin a for loop i in the range of 0-14
    a[i]=np.random.uniform(10,25)    #generating a random number between 10 - 25
    
a=np.reshape(a,(5,3)) #reshaping the array to the required form and printing
print("2D array of shape 5x3 to contain random float numbers between 10 and 25 \n",a,"\n")


2D array of shape 5x3 to contain random float numbers between 10 and 25 
 [[12.91021426 22.86294865 16.2753545 ]
 [16.36089478 11.33475103 12.37852102]
 [14.68952335 24.79036169 22.66221498]
 [17.68313193 12.53374883 14.83362718]
 [15.64197221 22.46825876 19.30999189]] 



### Question No: 07 - Take a string as input. Create a new string that is the reverse of the first string.


In [49]:
A ="Hello" # initializing the Identifier A as Hello

A[::-1]

olleH


### Question No: 08 A -  Write a Python program to remove the first occurrence of a specified element  from an array.


In [4]:
a = np.array([5,6,7,8,7,9,10,11,7,8,9,7,11])  #array Created
i=np.where(a==7) #finding the index of 7 in the arrray
i=i[0]                       #reassign i and choose 0 th element
#print(i,i[0])
np.delete(a,i[0])

array([ 5,  6,  8,  7,  9, 10, 11,  7,  8,  9,  7, 11])

### Question No: 08 B -  Write a Python program to remove the all occurrence of a specified element  from an array.

In [5]:
a = np.array([5,6,7,8,7,9,10,11,7,8,9,7,11]) #initializeed the array a
print(a[(a!=7)])                #printing the elements which statisfies the given condition 

[ 5  6  8  9 10 11  8  9 11]


### Question No: 09. Write a Python program that iterate over elements repeating each as many times as its count.

In [133]:
a=np.array([2,4,5,8]) #initializeed the array a

for i in a:         # Accessing individual elements from array a
    j=str(i)*i         #creating a copy of int values to str in the array j
    print(j)

22
4444
55555
88888888


### Question No: 10 A - Write a Python program to find the occurrences of 10 most common words in a given text.

In [2]:
from collections import Counter
import re
text = """Video provides a powerful way to help you prove your point. When you click Online Video, you can paste in the embed code for the video you want to add. You can also type a keyword to search online for the video that best fits your document.
To make your document look professionally produced, Word provides header, footer, cover page, and text box designs that complement each other. For example, you can add a matching cover page, header, and sidebar. Click Insert and then choose the elements you want from the different galleries.
Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme.
Save time in Word with new buttons that show up where you need them. To change the way a picture fits in your document, click it and a button for layout options appears next to it. When you work on a table, click where you want to add a row or a column, and then click the plus sign.
Reading is easier, too, in the new Reading view. You can collapse parts of the document and focus on the text you want. If you need to stop reading before you reach the end, Word remembers where you left off - even on another device.
"""
words = re.findall('\w+',text)
print(Counter(words).most_common(10))

[('you', 15), ('the', 13), ('a', 9), ('and', 9), ('to', 8), ('your', 7), ('click', 5), ('document', 5), ('new', 5), ('When', 4)]


### Question No: 10 B - Write a Python program to find the occurrences of 10 most common words which are at least 4 characters long in a given text.

In [34]:
import numpy as np #importing numpy
#print(words,type(words))
wd=['']
for i in words:
    if(len(i)>=4):
        wd.append(i)
print(Counter(wd).most_common(10))
#print(words[np.size(words)>=4])
#print(Counter(words[np.size(words)>=4]).most_common(10))

[('your', 7), ('click', 5), ('document', 5), ('When', 4), ('want', 4), ('that', 3), ('Word', 3), ('change', 3), ('where', 3), ('Video', 2)]


### Question No: 11 - Create a python program to generate the Fibonocci series.

In [26]:
import numpy as np

def fibo(n): 
    a=0
    b=1
    fib=np.array([a,b])
    if(n<0): 
        print("Incorrect input") 
    elif (n==0): 
        return a 
    elif (n==1): 
        return b 
    else: 
        for i in range(2,n): 
            c=a+b
            #print(c)
            a=b 
            b=c 
            fib=np.append(fib,c)
        return fib 

n=int(input("Enter the number of elements to be printed :"))
print(fibo(n)) 

Enter the number of elements to be printed :5
[0 1 1 2 3]
